name: Run htmltest

on: push

jobs:
  htmltest:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "latest"
    - name: Run Hugo
      run: hugo -s site -d $GITHUB_WORKSPACE/dist
    - name: Test HTML
      continue-on-error: true
      uses: wjdp/htmltest-action@master
      with:
        config: .htmltest.yml
    - name: Archive htmltest results
      uses: actions/upload-artifact@v2
      with:
        name: htmltest-report
        path: tmp/.htmltest/htmltest.log
        retention-days: 30 # Default is 90 days

